version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - CLIENT_BUILD_FLAVOR=any
    expose:
      - 80:80
    ports:
      - 80:80
    environment:
      HOMAS_API_KEY: apikey
      HOMAS_MONGO_URI: mongodb://db:27017/
    restart: always

  db:
    # Mongo with no authentication
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
